Fixed a stupid bug in the environment check
Fixed a bug where Tim would check for the default commands
(afplay/aplay) even when all different *_CMD variables was set with
something else in ~/.timrc. So if you wanted to use Tim with
afplay/aplay and you did set up the timrc file properly it would still
not run without one of them installed. Everything should work now :)

diff --git a/tim b/tim
--- a/tim
+++ b/tim
@@ -54,8 +54,10 @@ fi
 if [ -z $TIMER_CMD ]; then
   if [ -f ~/.tim/alarm.wav ]; then
     TIMER_CMD="$DEFAULT_CMD ~/.tim/alarm.wav"
+    USE_DEFAULT_CMD=1
   elif [ -f $DIRECTORY/audio_files/alarm.wav ]; then
     TIMER_CMD="$DEFAULT_CMD $DIRECTORY/audio_files/alarm.wav"
+    USE_DEFAULT_CMD=1
   else
     FILE_ERROR=1
   fi
@@ -64,8 +66,10 @@ fi
 if [ -z $WORK_CMD ]; then
   if [ -f ~/.tim/work.wav ]; then
     WORK_CMD="$DEFAULT_CMD ~/.tim/work.wav"
+    USE_DEFAULT_CMD=1
   elif [ -f $DIRECTORY/audio_files/work.wav ]; then
     WORK_CMD="$DEFAULT_CMD $DIRECTORY/audio_files/work.wav"
+    USE_DEFAULT_CMD=1
   else
     FILE_ERROR=1
   fi
@@ -74,8 +78,10 @@ fi
 if [ -z $BREAK_CMD ]; then
   if [ -f ~/.tim/break.wav ]; then
     BREAK_CMD="$DEFAULT_CMD ~/.tim/break.wav"
+    USE_DEFAULT_CMD=1
   elif [ -f $DIRECTORY/audio_files/break.wav ]; then
     BREAK_CMD="$DEFAULT_CMD $DIRECTORY/audio_files/break.wav"
+    USE_DEFAULT_CMD=1
   else
     FILE_ERROR=1
   fi
@@ -84,8 +90,10 @@ fi
 if [ -z $POMODORO_CMD ]; then
   if [ -f ~/.tim/alarm.wav ]; then
     POMODORO_CMD="$DEFAULT_CMD ~/.tim/alarm.wav"
+    USE_DEFAULT_CMD=1
   elif [ -f $DIRECTORY/audio_files/alarm.wav ]; then
     POMODORO_CMD="$DEFAULT_CMD $DIRECTORY/audio_files/alarm.wav"
+    USE_DEFAULT_CMD=1
   else
     FILE_ERROR=1
   fi
@@ -105,31 +113,33 @@ fi
 # VALIDATE SETTINGS SECTION                                                   #
 ###############################################################################
 function validate_settings {
-  A=(${(z)DEFAULT_CMD}) # Puts the value of DEFAULT_CMD into an array.
+  if [[ $USE_DEFAULT_CMD == 1 ]]; then
+    A=(${(z)DEFAULT_CMD}) # Puts the value of DEFAULT_CMD into an array.
 
-  if ! type -p $A[1] >& /dev/null; then # Checks if command exist.
-    if [[ $1 == debug ]]; then # Different output if debug mode is on.
-      echo "DEFAULT_CMD: Command '$A[1]' doesn't exist!" && ERROR=1
-    else
-      echo "Tim wants to use '$A[1]' but can't find it!
+    if ! type -p $A[1] >& /dev/null; then # Checks if command exist.
+      if [[ $1 == debug ]]; then # Different output if debug mode is on.
+        echo "DEFAULT_CMD: Command '$A[1]' doesn't exist!" && ERROR=1
+      else
+        echo "Tim wants to use '$A[1]' but can't find it!
 
 Install it or specify other command in your ~/.timrc file.
 Read the file timrc.example for more information."
 
-      ERROR=1 && return 1 # Set error flag and exit function.
+        ERROR=1 && return 1 # Set error flag and exit function.
+      fi
     fi
-  fi
 
-  if [[ $FILE_ERROR == 1 ]]; then
-    if [[ $1 == debug ]]; then
-      echo "Can't find the default audio files!" && ERROR=1
-    else
-      echo "Tim can't find the default audio files!
+    if [[ $FILE_ERROR == 1 ]]; then
+      if [[ $1 == debug ]]; then
+        echo "Can't find the default audio files!" && ERROR=1
+      else
+        echo "Tim can't find the default audio files!
 
 Put them in ~/.tim or specify other files in your ~/.timrc file.
 Read the file timrc.example for more information."
 
-      ERROR=1 && return 1 # Set error flag and exit function.
+        ERROR=1 && return 1 # Set error flag and exit function.
+      fi
     fi
   fi
 
