Version 1.1
Added reverse interval mode. The same as normal interval mode but you
start with a break. I always wanted that since i'm lazy :)

Fixed a bug that made tim --interval <number> fail.
Made all variables uppercase.
Added more comments through out the script.

diff --git a/tim b/tim
--- a/tim
+++ b/tim
@@ -29,7 +29,7 @@
 # Git: https://github.com/ggustafsson/Timer-Script-Improved                   #
 ###############################################################################
 
-VERSION=1.0.4
+VERSION=1.1
 FILENAME=$0:t # Get the current filename of the script.
 DIRECTORY=$0:A:h # Get the path of the directory the script is in.
 
@@ -105,18 +105,18 @@ fi
 # VALIDATE SETTINGS SECTION                                                   #
 ###############################################################################
 function validate_settings {
-  a=(${(z)DEFAULT_CMD}) # Puts the value of DEFAULT_CMD into an array.
+  A=(${(z)DEFAULT_CMD}) # Puts the value of DEFAULT_CMD into an array.
 
-  if ! type -p $a[1] >& /dev/null; then # Checks if command exist.
-    if [[ $1 == debug ]]; then
-      echo "DEFAULT_CMD: Command '$a[1]' doesn't exist!" && ERROR=1
+  if ! type -p $A[1] >& /dev/null; then # Checks if command exist.
+    if [[ $1 == debug ]]; then # Different output if debug mode is on.
+      echo "DEFAULT_CMD: Command '$A[1]' doesn't exist!" && ERROR=1
     else
-      echo "Tim wants to use '$a[1]' but can't find it!
+      echo "Tim wants to use '$A[1]' but can't find it!
 
 Install it or specify other command in your ~/.timrc file.
 Read the file timrc.example for more information."
 
-      ERROR=1 && return 1
+      ERROR=1 && return 1 # Set error flag and exit function.
     fi
   fi
 
@@ -129,33 +129,33 @@ Read the file timrc.example for more information."
 Put them in ~/.tim or specify other files in your ~/.timrc file.
 Read the file timrc.example for more information."
 
-      ERROR=1 && return 1
+      ERROR=1 && return 1 # Set error flag and exit function.
     fi
   fi
 
-  for x in $CMD_SETTINGS; do
-    b=(${(zP)x}) # Puts the value of the current variable into an array.
+  for X in $CMD_SETTINGS; do
+    B=(${(zP)X}) # Puts the value of the current variable into an array.
 
-    if ! type -p $b[1] >& /dev/null; then # Checks if command exist.
-      echo "$x: Command '$b[1]' doesn't exist!" && ERROR=1
+    if ! type -p $B[1] >& /dev/null; then # Checks if command exist.
+      echo "$X: Command '$B[1]' doesn't exist!" && ERROR=1
     fi
   done
 
-  for x in $RPT_SETTINGS; do
+  for X in $RPT_SETTINGS; do
     # Checks if the settings only contain numbers and have a value of 0/1.
-    if [[ ! ${(P)x} == <-> ]] || [[ ${(P)x} != [0-1] ]]; then
-      echo "$x: Setting '${(P)x}' is not valid." && ERROR=1
+    if [[ ! ${(P)X} == <-> ]] || [[ ${(P)X} != [0-1] ]]; then
+      echo "$X: Setting '${(P)X}' is not valid." && ERROR=1
     fi
   done
 
-  for x in $INT_SETTINGS; do
+  for X in $INT_SETTINGS; do
     # Checks if the settings only contain numbers and have a value above 0.
-    if [[ ! ${(P)x} == <-> ]] || [[ ${(P)x} < 1 ]]; then
-      echo "$x: Setting '${(P)x}' is not valid." && ERROR=1
+    if [[ ! ${(P)X} == <-> ]] || [[ ${(P)X} < 1 ]]; then
+      echo "$X: Setting '${(P)X}' is not valid." && ERROR=1
     fi
   done
 
-  [[ $1 == debug ]] && [[ $ERROR == 1 ]] && echo
+  [[ $1 == debug ]] && [[ $ERROR == 1 ]] && echo # echo if running debug mode.
 }
 
 
@@ -170,16 +170,17 @@ Try '--help' for more information."
 function help {
   echo "Usage: $FILENAME [OPTION]... [NUMBER]...
 
-  [NUMBER]                 Wait [NUMBER] minutes before starting alarm.
-  -i, --interval [NUMBER]  Work [NUMBER] minutes and pause [NUMBER] minutes.
-                            (Default: 15 minutes work and pause.)
-  -p, --pomodoro           Work X minutes and pause X minutes. Run X times.
-                            (Default: 25 minutes work, 5 minutes break and
-                             stop after 4 times.)
-                            <http://en.wikipedia.org/wiki/Pomodoro_Technique>
-  -d, --debug              Display value of all variables and exit.
-  -h, --help               Display this help and exit.
-  -v, --version            Output version information and exit.
+  [NUMBER]                   Wait [NUMBER] minutes before starting alarm.
+  -i, --interval [NUMBER]    Work [NUMBER] minutes and pause [NUMBER] minutes.
+                              (Default: 15 minutes work and pause.)
+  -ri, --rinterval [NUMBER]  Reverse. Start with break instead of work.
+  -p, --pomodoro             Work X minutes and pause X minutes. Run X times.
+                              (Default: 25 minutes work, 5 minutes break and
+                               stop after 4 times.)
+                              <http://en.wikipedia.org/wiki/Pomodoro_Technique>
+  -d, --debug                Display value of all variables and exit.
+  -h, --help                 Display this help and exit.
+  -v, --version              Output version information and exit.
 
 Examples:
 
@@ -209,9 +210,9 @@ Released under the BSD 2-Clause license."
 ###############################################################################
 function timer {
   validate_settings
-  [[ $ERROR == 1 ]] && return 1 # Terminates if there's a problem with timrc.
+  [[ $ERROR == 1 ]] && return 1 # Terminate if there's a problem with timrc.
 
-  (( MINUTES_IN_SECONDS = $1 * 60 ))
+  (( MINUTES_IN_SECONDS = $1 * 60 )) # Convert minutes to seconds.
 
   echo -n "Starting timer. Waiting for $1 "
   if [[ $1 > 1 ]]; then
@@ -239,16 +240,26 @@ function timer {
 ###############################################################################
 function interval {
   validate_settings
-  [[ $ERROR == 1 ]] && return 1 # Terminates if there's a problem with timrc.
+  [[ $ERROR == 1 ]] && return 1 # Terminate if there's a problem with timrc.
 
-  if [[ -z $1 ]]; then
+  if [[ $1 == reverse ]]; then
+    SPECIFIC_TIME=$2
+  else
+    SPECIFIC_TIME=$1
+  fi
+
+  if [ -z $SPECIFIC_TIME ]; then
     MINUTES=$INTERVAL
   else
-    MINUTES=$1
+    MINUTES=$SPECIFIC_TIME
   fi
   (( MINUTES_IN_SECONDS = $MINUTES * 60 ))
 
-  CURRENT_MODE=work
+  if [[ $1 == reverse ]]; then
+    CURRENT_MODE=break
+  else
+    CURRENT_MODE=work
+  fi
 
   echo -n "Starting timer. Interval of $MINUTES "
   if [[ $MINUTES > 1 ]]; then
@@ -256,7 +267,13 @@ function interval {
   else
     echo "minute."
   fi
-  echo "Start working now. Stop with Ctrl+C."
+  echo -n "Start "
+  if [[ $CURRENT_MODE == work ]]; then
+    echo -n "working"
+  else
+    echo -n "break"
+  fi
+  echo " now. Stop with Ctrl+C."
 
   while true; do
     sleep $MINUTES_IN_SECONDS
@@ -269,7 +286,7 @@ function interval {
 
       CURRENT_MODE=break
     else
-      print -P "%B%F{red}START WORKING AGAIN!%f%b"
+      print -P "%B%F{red}START WORKING NOW!%f%b"
       eval $WORK_CMD
 
       CURRENT_MODE=work
@@ -283,8 +300,9 @@ function interval {
 ###############################################################################
 function pomodoro {
   validate_settings
-  [[ $ERROR == 1 ]] && return 1 # Terminates if there's a problem with timrc.
+  [[ $ERROR == 1 ]] && return 1 # Terminate if there's a problem with timrc.
 
+  # Convert minutes to seconds.
   (( POMODORO_WORK_IN_SECONDS  = $POMODORO_WORK  * 60 ))
   (( POMODORO_BREAK_IN_SECONDS = $POMODORO_BREAK * 60 ))
 
@@ -309,12 +327,13 @@ Start working now. Stop with Ctrl+C."
       CURRENT_MODE=break
       MINUTES_IN_SECONDS=$POMODORO_BREAK_IN_SECONDS
     else
-      print -P "%B%F{red}START WORKING AGAIN!%f%b"
+      print -P "%B%F{red}START WORKING NOW!%f%b"
       eval $WORK_CMD
 
       CURRENT_MODE=work
       MINUTES_IN_SECONDS=$POMODORO_WORK_IN_SECONDS
 
+      # Increment CURRENT_RUN so we can stop pomodoro mode at POMODORO_STOP.
       (( CURRENT_RUN = $CURRENT_RUN + 1 ))
     fi
   done
@@ -324,10 +343,10 @@ Start working now. Stop with Ctrl+C."
 
   if [[ $POMODORO_REPEAT_ALARM == 1 ]]; then
     while true; do
-      eval $POMODORO_CMD
+      eval $POMODORO_CMD # Execute POMODORO_CMD and loop until terminating.
     done
   else
-    eval $POMODORO_CMD
+    eval $POMODORO_CMD # Execute POMODORO_CMD.
   fi
 }
 
@@ -338,7 +357,7 @@ Start working now. Stop with Ctrl+C."
 function debug {
   echo "DEBUG MODE\n"
 
-  validate_settings debug
+  validate_settings debug # Send argument debug to function for more output.
 
   echo "VALUE OF ALL VARIABLES:
  FILENAME: $FILENAME
@@ -346,16 +365,17 @@ function debug {
  VERSION: $VERSION
  DEFAULT_CMD: $DEFAULT_CMD"
 
-  for x in $CMD_SETTINGS; do
-    echo " $x: ${(P)x}"
+  # Loop thru all settings and print them out.
+  for X in $CMD_SETTINGS; do
+    echo " $X: ${(P)X}"
   done
 
-  for x in $RPT_SETTINGS; do
-    echo " $x: ${(P)x}"
+  for X in $RPT_SETTINGS; do
+    echo " $X: ${(P)X}"
   done
 
-  for x in $INT_SETTINGS; do
-    echo " $x: ${(P)x}"
+  for X in $INT_SETTINGS; do
+    echo " $X: ${(P)X}"
   done
 }
 
@@ -369,25 +389,34 @@ case $# in
     case $1 in
       <->) # Check if $1 only contain numbers.
         if [[ $1 > 0 ]]; then
-          timer $1 # Send argument $1 to the function timer.
+          timer $1 # Send argument $1 to the function.
         else
           usage && return 1
         fi
       ;;
-      -i | --interval) interval ;;
-      -p | --pomodoro) pomodoro ;;
-      -d | --debug)    debug    ;;
-      -h | --help)     help     ;;
-      -v | --version)  version  ;;
+      -i  | --interval)  interval         ;;
+      -ri | --rinterval) interval reverse ;;
+      -p  | --pomodoro)  pomodoro         ;;
+      -d  | --debug)     debug            ;;
+      -h  | --help)      help             ;;
+      -v  | --version)   version          ;;
       *)
         usage && return 1
       ;;
     esac
   ;;
   2)
-    if [[ $1 == -i ]] && [[ $2 == <-> ]]; then # Check if $2 is integer.
-      if [[ $2 > 0 ]]; then
-        interval $2 # Send argument $2 to the function interval.
+    # Check if $1 is -i or --interval and if $2 is integer.
+    if [[ $1 == -i ]] || [[ $1 == --interval ]] && [[ $2 == <-> ]]; then
+      if [[ $2 > 0 ]]; then # Check if integer is more than 0.
+        interval $2 # Send argument $2 to the function.
+      else
+        usage && return 1
+      fi
+    # Check if $1 is -ri or --rinterval and if $2 is integer.
+    elif [[ $1 == -ri ]] || [[ $1 == --rinterval ]] && [[ $2 == <-> ]]; then
+      if [[ $2 > 0 ]]; then # Check if integer is more than 0.
+        interval reverse $2 # Send argument reverse and $2 to the function.
       else
         usage && return 1
       fi
